class medicamento {
    Codigo = ""
    nomeComercial = ""
    nomeGenerico = ""
    codCategoria = ""
    lote = ""
    validade = ""
    preco = ""
    precoDesconto = ""
    dataCompra = ""
    codFornecedor= ""
    fonteCompra = ""
    dosagem = ""
    quantidade = ""
    descricao = ""
    codLaboratorio = ""
    tipoDeUso = ""
    dataInício = ""
    previsaoTerminoCaixa = ""
}